defaults:
  - _self_

model: "adalal/smolvla-libero-64-2.0"

target: ???
k: ???
alpha: ???
# top_k_tokens: ???

eval:
  batch_size: 2
  n_episodes: 2
  # condition_label: up

policy:
  n_action_steps: 10
  path: "${model}"

sweep_name: "default_sweep"


# target: up
# k: 3
# alpha: 0.05
# top_k_tokens: 5

# eval:
#   batch_size: 2
#   n_episodes: 2

# policy:
#   n_action_steps: 10
#   path: "${model}"

# sweep_name: "default_sweep"

